spring:
  debug: true
#     mvc:
# 配置jsp文件的位置，默认位置为：src/main/webapp
#         view.prefix: /WEB-INF/jsp/
#         view.suffix: .jsp
  aop:
    proxy-target-class: true
  thymeleaf:
    cache: false
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
    multipart.maxFileSize: 1024MB
    multipart.maxRequestSize: 1024MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bwb?useUnicode=true&amp;characterEncoding=utf-8
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    #filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
jpa:
  database: MYSQL
  hibernate:
    ddl-auto: update //自动更新
  show-sql: true  //日志中显示sql语句
server:
  port: 8888
files.docservice.url.api: http://127.0.0.1/web-apps/apps/api/documents/api.js
fileServer:
  domain: http://172.16.17.75:8888
filemanager:
  root: E:/file
debug: true